INSERT INTO Books (Title, Writer, Publisher, PublishDate, Description, SuppliersSupID, CategoriesCategoryID) VALUES 
	('Belajar SQL dari Dasar', 'Ahmad Zulkarnain', 'Pustaka Coding', '2019-01-15', 'Panduan lengkap SQL untuk pemula', 1, 1),
	('Pemrograman Python', 'Siti Aminah', 'Informatika Nusantara', '2020-03-10', 'Dasar-dasar pemrograman Python', 2, 2),
 	('Data Science untuk Semua', 'Dewi Ratna', 'PT Ilmu Terapan', '2021-06-15', 'Pengenalan Data Science', 3, 3),
 	('Machine Learning Praktis', 'Agus Prasetyo', 'Tech Media', '2018-11-20', 'Implementasi machine learning', 4, 4),
 	('Deep Learning dengan Python', 'Wulan Maharani', 'Kode Publisher', '2021-02-25', 'Teknik deep learning', 5, 2),
	('Analisis Data dengan R', 'Budi Setiawan', 'Data Solusi', '2022-08-05', 'Analisis data menggunakan R', 6, 1),
 	('Pemrograman Java', 'Santi Handayani', 'Edukasi Nusantara', '2017-10-11', 'Panduan Java dari dasar', 7, 2),
 	('Manajemen Proyek IT', 'Mulyadi', 'Pustaka Proyek', '2019-07-09', 'Dasar manajemen proyek IT', 8, 5),
 	('Komputasi Awan untuk Pemula', 'Indah Pertiwi', 'Tekno Media', '2020-05-22', 'Pengenalan komputasi awan', 9, 6),
	('Keamanan Siber', 'Cahyo Adi', 'PT Cyberindo', '2021-11-30', 'Panduan keamanan siber', 10, 4),
	('Pemrograman Mobile dengan Android', 'Sinta Amalia', 'Mobilindo', '2016-04-18', 'Pemrograman Android untuk pemula', 11, 2),
	('Teknik Big Data', 'Hendrik Susanto', 'Data Media', '2018-08-01', 'Teknologi big data terkini', 12, 3),
	('Pemrograman C++', 'Rina Safitri', 'PT Koding Kita', '2019-09-11', 'Pemrograman C++ dari dasar', 13, 2),
	('Algoritma dan Struktur Data', 'Sudirman', 'Algo Media', '2017-02-13', 'Konsep algoritma dan struktur data', 14, 1),
	('Jaringan Komputer', 'Lestari Dewi', 'Jaringan Publisher', '2020-09-30', 'Konsep jaringan komputer', 15, 6),
	('Sistem Operasi', 'Teguh Priyanto', 'PT Sistem Solusi', '2018-12-12', 'Pengantar sistem operasi', 16, 1),
 	('Pemrograman PHP dan MySQL', 'Novi Andriani', 'Web Publisher', '2022-03-01', 'Membangun aplikasi web', 17, 2),
 	('Desain UI/UX', 'Rahmat Hidayat', 'Design Media', '2021-05-15', 'Panduan desain UI/UX', 18, 7),
 	('Digital Marketing', 'Ratna Putri', 'Media Online', '2019-12-01', 'Teknik pemasaran digital', 19, 5),
 	('Web Development', 'Dian Kurnia', 'Web Media', '2020-06-11', 'Pengembangan web dari dasar', 20, 2),
 	('Game Development', 'Aldi Firman', 'Game Studio', '2018-10-01', 'Pengenalan pengembangan game', 21, 8),
 	('Pemrograman Kotlin', 'Yusuf Pranoto', 'Mobile Code', '2021-01-07', 'Pemrograman Kotlin untuk Android', 22, 2),
 	('Machine Learning untuk Bisnis', 'Nadia Sari', 'Business Tech', '2020-11-15', 'Implementasi ML dalam bisnis', 23, 4),
 	('Analisis Keuangan dengan Excel', 'Edi Pratama', 'Finance Publisher', '2019-03-12', 'Analisis data keuangan', 24, 5),
 	('Pemrograman Rust', 'Sri Wahyuni', 'Rust Academy', '2019-05-20', 'Dasar-dasar pemrograman Rust', 25, 2),
	('Agile Project Management', 'Ardi Suherman', 'Agile Solutions', '2020-02-22', 'Pendekatan agile dalam proyek', 26, 5),
	('Analisis Risiko IT', 'Maya Sari', 'Risk Management', '2021-04-17', 'Pengelolaan risiko di IT', 27, 6),
	('Pemrograman Swift', 'Tono Wijaya', 'iOS Dev', '2018-09-28', 'Pemrograman Swift untuk iOS', 28, 2),
 	('Kecerdasan Buatan', 'Indra Kusuma', 'AI Publisher', '2019-10-19', 'Konsep kecerdasan buatan', 29, 3),
	('Teknik Jaringan Komputer', 'Rudi Hartono', 'Network Media', '2020-08-25', 'Teknik membangun jaringan', 30, 6);
