INSERT INTO Categories (CategoryName) VALUES 
	('SQL'),
 	('Python Programming'),
 	('Data Science'),
 	('Machine Learning'),
 	('Project Management'),
 	('Cloud Computing'),
	('Cyber Security'),
 	('Mobile Development'),
 	('Big Data'),
 	('C++ Programming'),
 	('Algorithms'),
 	('Computer Networks'),
 	('Operating Systems'),
	('Web Development'),
 	('UI/UX Design'),
 	('Digital Marketing'),
	('Game Development'),
 	('Kotlin Programming'),
 	('Business Technology'),
 	('Financial Analysis'),
 	('Rust Programming'),
 	('Agile Methodology'),
 	('IT Risk Management'),
 	('Swift Programming'),
 	('Artificial Intelligence'),
	('Network Engineering'),
 	('Java Programming'),
 	('Data Analysis'),
 	('Excel for Finance'),
	('Information Technology');
